name: Moving files from google storage to google drive
run-name: ${{ github.actor }} moving files from google storage to google drive 🚀
on: 
  workflow_dispatch:
    inputs:
      gcp_prefix:
        description: 'gcp path prefix'
        required: true
        default: ''
      team_driver_id:
        description: 'google drive team drive id'
        required: true
        default: '' 
      dest_folder_id:
        description: 'google drive destination folder id'
        required: true
        default: ''         
    # agendamento para execucao todo dia as 8:00 da manhã
  schedule:
    - cron:  '0 8 * * *'
jobs:
  Moving-Data-Using-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: 'google-auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - name: 'install gcsfuse to access bucket'
        run: |
          export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
          echo "deb https://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install gcsfuse

          export INPUT_DIR=${{ github.workspace }}/google-storage          
          mkdir ${INPUT_DIR}

          sudo groupadd fuse
          sudo usermod -a -G fuse $USER
          sudo chown $USER_ID:fuse ${INPUT_DIR}
         
          gcsfuse --dir-mode=777 --file-mode=777 --key-file=$GOOGLE_APPLICATION_CREDENTIALS --implicit-dirs ${{ secrets.gcp_bucket }} ${INPUT_DIR}
      - name: 'install and config google-drive-ocamlfuse to access google drive'
        run: |
          sudo add-apt-repository --yes ppa:alessandro-strada/ppa
          sudo apt-get update
          sudo apt-get install google-drive-ocamlfuse

          export OUTPUT_DIR=${{ github.workspace }}/google-drive
          mkdir ${OUTPUT_DIR}

          export XDG_CONFIG_HOME=${{ github.workspace }}
          mkdir ${XDG_CONFIG_HOME}/gdfuse
          chmod o+w  ${XDG_CONFIG_HOME}/gdfuse/.
          export GD_JSON_FILE=${{ github.workspace }}/gdfuse/gd_credentials.json
          cat GD_JSON_FILE
          echo ${{ secrets.gd_credentials }} > ${GD_JSON_FILE}
          !google-drive-ocamlfuse -xdgbd -label mylabel -serviceaccountpath ${GD_JSON_FILE} -serviceaccountuser ${{ secrets.gd_account_service }}
          export TEAM_DRIVER_ID=${{ github.event.inputs.team_driver_id}}
          export GDFUSE_CONFIG_PATH=${XDG_CONFIG_HOME}/gdfuse/mylabel/config
          python3 ./code/config_gdfuse.py
          google-drive-ocamlfuse -cc -label mylabel ${OUTPUT_DIR}          
          
      - name: Prepare permissions, scripts and call script to collect files
        working-directory: ./code
        run: |
          export OUTPUT_DIR=${{ github.workspace }}/output-files/${{ github.event.inputs.gcp_prefix}}
          export GCP_PREFIX=${{ github.event.inputs.gcp_prefix}}
          export TEAM_DRIVER_ID=${{ github.event.inputs.team_driver_id}}
          export DEST_FOLDER_ID=${{ github.event.inputs.dest_folder_id}}          
          pip3 install -r ../requirements.txt
          python3 ./main.py

      - run: echo "🍏 This job's status is ${{ job.status }}."
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
